"""user_is_bot

Revision ID: bef7e803bc25
Revises: 3c5a2012ecae
Create Date: 2024-09-15 17:09:42.745737

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bef7e803bc25"
down_revision = "3c5a2012ecae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_user_info",
        sa.Column("is_bot", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_user_info", "is_bot")
    # ### end Alembic commands ###
